CREATE TABLE IF NOT EXISTS customers (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    billing_address VARCHAR(255) NOT NULL,
    delivery_address VARCHAR(255) DEFAULT NULL,
    deleted_at DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    routing_key VARCHAR(104) NOT NULL,
    exchange VARCHAR(100) NOT NULL,
    body VARBINARY NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);