version: '3'
services:
  rabbitmq:
    image: 'rabbitmq'
    networks:
      - infra
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq'
      - './rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - infra

volumes:
  rabbitmq:
    driver: local

networks:
  infra:
    driver: bridge
    name: fgto-infra
