version: '3'
services:
  customers:
    image: 'eclipse-temurin:17-jdk-alpine'
    working_dir: '/app'
    command: ["./gradlew", "bootRun"]
    ports:
      - '8080:8080'
    networks:
      - infra
      - customers
    volumes:
      - '.:/app'
    environment:
      AMQP_HOST: '${AMQP_HOST:-localhost}'
      AMQP_PORT: '${AMQP_PORT:-3356}'
      AMQP_USERNAME: '${AMQP_USERNAME:-guest}'
      AMQP_PASSWORD: '${AMQP_PASSWORD:-guest}'

      DATABASE_HOST: '${DATABASE_HOST:-localhost}'
      DATABASE_USER: '${DATABASE_USER:-username}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD:-password}'
      DATABASE_NAME: '${DATABASE_NAME:-customers}'

  database:
    image: 'postgres:15'
    networks:
      - customers
    volumes:
      - 'postgres:/var/lib/postgres'
    environment:
      POSTGRES_USER: '${DATABASE_USER:-username}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD:-password}'
      POSTGRES_DB: '${DATABASE_NAME:-customers}'
    ports:
      - '${DATABASE_PORT_FORWARD:-5432}:${DATABASE_PORT:-5432}'

volumes:
  postgres:
    driver: local

networks:
  customers:
    driver: bridge
  infra:
    name: fgto-infra
    external: true
